version: 2.1

###########################################
# Constants
###########################################
workspace_root: &workspace_root
    /tmp/workspace

defaults: &defaults
    working_directory: *workspace_root

###########################################
# Executor Definitions
###########################################
executors:
    build_executor:
        <<: *defaults
        docker:
            - image: circleci/node:10.11.0

###########################################
# Job Definitions
###########################################
jobs:
    prepare:
        executor: build_executor
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: make init -j
            - persist_to_workspace:
                root: *workspace_root
                paths:
                    - "./*"

    test:
        executor: build_executor
        steps:
            - attach_workspace:
                at: *workspace_root
            # FIXME: https://github.com/o2project/steins-git/issues/148
            # - run:
            #     name: Lint
            #     command: make lint -j
            # FIXME: https://github.com/o2project/steins-git/issues/147
            # - run:
            #     name: Check formatted sources
            #     command: make check_format -j

###########################################
# Workflow Definitions
###########################################
workflows:
    version: 2
    test_flow:
        jobs:
            - prepare
            - test:
                requires:
                    - prepare
